apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: bbj
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 30
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do echo hello; sleep 10;done
        image: busybox
        name: bbj
        resources: {}
      restartPolicy: Never
status: {}
