apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lifecycle-demo-container
  name: lifecycle-demo-container
spec:
  containers:
  - image: nginx
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
      preStop:
        exec:
          command: ["/bin/sh", "-c", "nginx -s quit; while kilall -0 nginx; do sleep 1; done"]
    name: lifecycle-demo-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
