apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-08-29T05:28:07Z"
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "333842"
  uid: 5fb54686-5853-41b4-9d91-daca811ada2d
spec:
  containers:
  - image: nginx
    volumeMounts:
    - name: share
      mountPath: /usr/share/nginx/html
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: share
    emptyDir: {} 
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'wget -O /work-dir/index.html http://neverssl.com/online']
    volumeMounts:
    - name: share
      mountPath: /work-dir
   
