apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: memory-demo
  name: memory-demo
spec:
  containers:
  - image: polinux/stress
    name: memory-demo
    resources: 
      limits:
        memory: "100Mi"
      requests:
        memory: "50Mi"
    command: ["stress"]
    args: ["--vm","1","--vm-bytes","250M","--vm-hang","1"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
