apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
      exec: 
        command: 
        - ls
    readinessProbe:
      httpGet:
        port: 80
        path: /
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
